const ADD_TODO = "ADD_TODO";
const LOAD_DATA = "LOAD_DATA";
const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
const SHOW_ALL = "SHOW_ALL";
const SHOW_COMPLETE = "SHOW_COMPLETE";
const SHOW_TODO = "SHOW_TODO";

export {
  ADD_TODO,
  LOAD_DATA,
  TOGGLE_COMPLETE,
  SHOW_ALL,
  SHOW_COMPLETE,
  SHOW_TODO
};
